### PR TITLE
fix(slide): Make links in slides clickable

### LINKED ISSUE #133: Can't click links inside slider
The pointer-events:none is preventing me from clicking links inside slider, I can't disabled it?

### PR DESCRIPTION
**Pull request by mstruebing**
closes #133

### CODE REVIEW

**Review by Kampfheizung — COMMENTED** [review]
Could we also provide an example that has full size images with links wrapped around? I guess than we would have a problem with the right/left arrows at the side, right?

**Comment by mstruebing** [comment]
You mean that the whole slide (which would be an image) would be a link?

**Comment by Kampfheizung** [comment]
> You mean that the whole slide (which would be an image) would be a link?

**Comment by mstruebing** [comment]
The problem is: if the slide is a link and we would slide via "drag and drop" the link would be "executed" and not the slide event.
So I guess making a whole slide a link doesn't really makes sense.

**Comment by Kampfheizung** [comment]
> The problem is: if the slide is a link and we would slide via "drag and drop" the link would be "executed" and not the slide event.
> So I guess making a whole slide a link doesn't really makes sense.

Okay than just let's wait for a request if this feature is wanted 👍

**Review by Kampfheizung — APPROVED** [review]

**Comment by mstruebing** [comment]
I agree, what we would need to do then would be simply the option to disable "drag and drop" sliding and be able to only slide via the controls (arrows, bullets, automatically by times)

**Pull request merged**
